### ISSUE TITLE
Cannot read the array length because "sigBytes" is null

### ISSUE THREAD

**Issue by musttafayildirim** [HuaJI66/JrebelLicenseServer#1]
I'am using latest version Intellij Idea but your activation give me error. 

Cannot read the array length because "sigBytes" is null

What can we do about this?

**Comment by HuaJI66** [comment]
> I'am using latest version Intellij Idea but your activation give me error.
> 
> Cannot read the array length because "sigBytes" is null
> 
> What can we do about this?

You can try using this version of the [JRebel and XRebel ](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=482139) plugin with  [IntelliJ IDEA 2024.1.1](https://www.jetbrains.com/idea/download/other.html)
